services:
  - type: web
    name: backpack-backend
    env: docker
    region: ohio
    plan: free
    rootDir: backend
    healthCheckPath: /
    disk:
      name: backport-db
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: PORT
        value: "10000"
      - key: DB_PATH
        value: "/app/data/backport.db"
      - key: SECRET_KEY
        generateValue: true
      - key: RAZORPAY_KEY_ID
        value: ""
      - key: RAZORPAY_KEY_SECRET
        value: ""
